# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: ['--', '-D', 'warnings', '-A', 'dead-code']

  - repo: local
    hooks:
      - id: elm-review
        name: elm-review
        language: system
        entry: npx elm-review
        files: \.elm$
        pass_filenames: false
        args:
          - "--ignore-dirs"
          - .elm-spa
          - "--elmjson"
          - spa/elm.json

      - id: elm-format
        name: elm-format
        language: system
        entry: elm-format
        files: \.elm$
        args:
          - "--validate"
