# -*- restclient -*-

:swaf = http://localhost:8000

# Health check
GET :swaf/health

# Login
POST :swaf/login

# Get the current user's details
GET :swaf/user/current
Accept: application/json

# Download test file
GET :swaf/file/hi.txt
