# -*- restclient -*-

:swaf = http://localhost:8000/api

# Health check
GET :swaf/health

# Login
POST :swaf/login
Content-type: application/x-www-form-urlencoded
login_name=dan&password=thisismypassword&

# Logout
GET :swaf/logout

# Get the current user's details
GET :swaf/user/current
Accept: application/json

# List users
GET :swaf/users
Accept: application/json

# List groups
GET :swaf/groups
Accept: application/json

# Download test file
GET :swaf/file/hi.txt

# Get file metadata
GET :swaf/meta/subdir

# Get directory listing
GET :swaf/ls/

# Upload small file
PUT :swaf/file/test_again.txt
Content-type: text/plain

<repo/file_root/test.txt

# Upload larger file
PUT :swaf/file/screenshot.png
Content-type: image/png

<repo/screenshot1.png


# Create a user
PUT :swaf/user
Content-type: application/json
{
"login_name": "dan",
"full_name": "Dan",
"groups": [],
"policy_statements":[]
}

# Update a user
POST :swaf/user
Content-type: application/json
{
"login_name": "dan",
"full_name": "Danton",
"groups": [],
"policy_statements":[{
  "effect": "Allow",
  "actions":["*"],
  "resources":["*"]
}]
}

# Set user password
POST :swaf/user/dan/password
Content-type: text/plain
thisismypassword
