name: Build, test, and release

on:
  push:
    branches: '*'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install elm
        run: npm install -yg elm elm-format

      - name: Generate elm-spa (needed for pre-commit checks)
        run: |
          pushd spa
          npx -y elm-spa gen
          popd

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit checks
        run: pre-commit run -a

      - name: Run Rust tests
        run: cargo test

      - name: Run Elm tests
        run: |
          pushd spa
          npx -y elm-test-rs
          popd

      - name: Build SPA
        run:  |
          pushd spa
          npx -y elm-spa build
          popd

      - name: Build back-end
        run: cargo build -r

      # - name: Docker Hub Login
      #   uses: docker/login-action@v1.9.0
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: ${{ matrix.target }}
          tags: swaf:latest

      - name: Docker Hub Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          target: ${{ matrix.target }}
          push: true
          tags: |
            sigcorp/swaf:latest
            sigcorp/swaf:preview-${{ github.run_number }}
